### ISSUE TITLE
Add lockedBalance to overview page

### ISSUE THREAD

**Issue by ghost** [spreadcoin/spreadcoin#2]
Only have "Balance:" and "Unconfirmed:" on the main screen. One feature I like is having a sum function just below. Someone mentioned awhile back about creating another line to include "Servernodes:" so that you will know exactly how much is locked into a servernode.

**Comment by cryptoons** [comment]
That's a good idea. 
Also, we could diplay "Sum" and "Servernodes" only if they are actually needed,
and hide them otherwise.

**Comment by njs811271** [comment]
One of the major perks for this coin is user friendliness.  Adding details like this to the wallet will definitely increase usability.

**Comment by ghost** [comment]
Closing: a “Locked” field that displays the sum of locked amounts was implemented for the overview page back in commit 2839dca
